// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe8joiaP1sX66wLFsDUoswkWUd_oZaDSg',
    appId: '1:855168810737:web:db57011b514136fef3f350',
    messagingSenderId: '855168810737',
    projectId: 'municipality-app-3cbcc',
    authDomain: 'municipality-app-3cbcc.firebaseapp.com',
    storageBucket: 'municipality-app-3cbcc.firebasestorage.app',
    measurementId: 'G-H2NZSSWFYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWz5zC3mQRp02L9KIZzD0oF1cYRofLVc',
    appId: '1:855168810737:android:a6347b1e797a423af3f350',
    messagingSenderId: '855168810737',
    projectId: 'municipality-app-3cbcc',
    storageBucket: 'municipality-app-3cbcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9R4Bj0QsGFHt-vbU0KylP45VS95-_7j0',
    appId: '1:855168810737:ios:a950f8abf30397e3f3f350',
    messagingSenderId: '855168810737',
    projectId: 'municipality-app-3cbcc',
    storageBucket: 'municipality-app-3cbcc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9R4Bj0QsGFHt-vbU0KylP45VS95-_7j0',
    appId: '1:855168810737:ios:a950f8abf30397e3f3f350',
    messagingSenderId: '855168810737',
    projectId: 'municipality-app-3cbcc',
    storageBucket: 'municipality-app-3cbcc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe8joiaP1sX66wLFsDUoswkWUd_oZaDSg',
    appId: '1:855168810737:web:a35e8233cf0f1eb4f3f350',
    messagingSenderId: '855168810737',
    projectId: 'municipality-app-3cbcc',
    authDomain: 'municipality-app-3cbcc.firebaseapp.com',
    storageBucket: 'municipality-app-3cbcc.firebasestorage.app',
    measurementId: 'G-H13KTPMW45',
  );
}
